---
title: "Data Analysis"
format: html
editor: visual
---

Packages

```{r}
#install.packages("tidyverse")
#install.packages("dplyr")
#install.packages("agricolae")
#install.packages("plotrix")
library(plotrix)
library(tidyverse)
library(dbplyr)
library(agricolae)
```

**Read in Data**

```{r}
DF <-read.csv("Master Water.csv", header=T)
```

**Clean Data**

```{r}

DF <- DF[, !(names(DF) %in% c("X", "X.1","X.2","X.3","X.4","X.5"))]

DF$NH4[DF$NH4=="LOD"]<-0
DF$Nitrate[DF$Nitrate=="LOD"]<-0
DF$Mg[DF$Mg=="LOD"]<-0
DF$P[DF$P=="LOD"]<-0

DF$Nitrate[DF$Nitrate < 0] <- 0


```

```{r}
DF$NH4  <- as.numeric(DF$NH4)  
DF$Nitrate  <- as.numeric(DF$Nitrate)
DF$Mg  <- as.numeric(DF$Mg)  
DF$P  <- as.numeric(DF$P)
DF$EC  <- as.numeric(DF$EC)
DF$pH  <- as.numeric(DF$pH)

DF$Treatment  <- as.factor(DF$Treatment) 
DF$Block  <- as.factor(DF$Block) 
DF$Site  <- as.factor(DF$Site) 
DF$Study.Year  <- as.factor(DF$Study.Year)

DF$Date <- as.Date(DF$Date, format = "%m_%d_%y")
                      
#unique(DF$Date)
#str(DF)
```

DATA ANALYSIS Mg

```{r}
df.summaryMg <- DF %>%
  group_by(Treatment, Date) %>%
  summarize(
    sd=sd(Mg, na.rm = TRUE),
    se=(sd/(sqrt(length(Mg)))),
    #se.1=std.error(Mg), 
    Mgmean = mean(Mg, na.rm = TRUE)
    )
df.summaryMg

Mg1<-lm(Mg~Treatment+Block+Site+Date,data=DF)
summary(Mg1)

Mg2<-aov(Mg1)
summary(Mg2)

tukey.testMg<-HSD.test(Mg2,trt="Treatment")
tukey.testMg


```

Data Visualization Mg

```{r}
ggplot(df.summaryMg, aes(Date, Mgmean, color = Treatment)) +
  geom_jitter(position = position_jitter(0.2)) + 
  geom_line(aes(group = Treatment),data = df.summaryMg) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)
  )+
  geom_errorbar(aes(ymin = Mgmean-se, ymax = Mgmean+se), data = df.summaryMg, width = 0.2)+
 
  theme(legend.position = "top")+
  ylab("Mg (mg/L)")


ggplot(df.summaryMg, aes(x = Treatment, y = Mgmean, fill = Treatment)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  
  labs(
       x = "Treatment",
       y = "Average Mg (mg/L)",
       fill = "Treatment") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

Data Analysis Nitrate

```{r}
df.summaryNitrate <- DF %>%
  group_by(Treatment, Date) %>%
  summarize(
    sd=sd(Nitrate, na.rm = TRUE),
    se=(sd/(sqrt(length(Nitrate)))),
    #se.1=std.error(Mg), 
    Nitrate = mean(Nitrate, na.rm = TRUE)
    )
df.summaryNitrate

Nitrate1<-lm(Nitrate~Treatment+Block+Site+Date+Date*Treatment+Treatment*Site,data=DF)
summary(Nitrate1)

Nitrate2<-aov(Nitrate1)
summary(Nitrate2)

tukey.testNitrate<-HSD.test(Nitrate2,trt="Treatment")
tukey.testNitrate


```

Nitrate for Unique Dates

```{r}


time1<-filter(DF,Date=="2023-12-27")

TimeLM<-lm(Nitrate~Treatment+Block+Site+Treatment*Site,data=time1)
summary(TimeLM)

TM1<-aov(TimeLM)
summary(TM1)

tukey.testNitrate<-HSD.test(Nitrate2,trt="Treatment")
tukey.testNitrate
```

Data Visualization Nitrate

```{r}
ggplot(df.summaryNitrate, aes(Date, Nitrate, color = Treatment)) +
  geom_jitter(position = position_jitter(0.2)) + 
  geom_line(aes(group = Treatment),data = df.summaryNitrate) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)
  )+
  geom_errorbar(aes(ymin = Nitrate-se, ymax = Nitrate+se), data = df.summaryNitrate, width = 0.2)+
 
  theme(legend.position = "top")+
  ylab("Nitrate (mg/L)")
```

Data Analysis NH4

```{r}
df.summaryNH4 <- DF %>%
  group_by(Treatment, Date) %>%
  summarize(
    sd=sd(NH4, na.rm = TRUE),
    se=(sd/(sqrt(length(NH4)))),
    #se.1=std.error(Mg), 
    NH4 = mean(NH4, na.rm = TRUE)
    )
df.summaryNH4

NH41<-lm(NH4~Treatment+Block+Site+Date,data=DF)
summary(NH41)

NH42<-aov(NH41)
summary(NH42)

tukey.testNH4<-HSD.test(NH42,trt="Treatment")
tukey.testNH4
```

Data Visualization NH4

```{r}
ggplot(df.summaryNH4, aes(Date, NH4, color = Treatment)) +
  geom_jitter(position = position_jitter(0.2)) + 
  geom_line(aes(group = Treatment),data = df.summaryNH4) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)
  )+
  geom_errorbar(aes(ymin = NH4-se, ymax = NH4+se), data = df.summaryNH4, width = 0.2)+
 
  theme(legend.position = "top")+
  ylab("NH4 (mg/L)")
```

Data Analysis P

```{r}
df.summaryP <- DF %>%
  group_by(Treatment, Date) %>%
  summarize(
    sd=sd(P, na.rm = TRUE),
    se=(sd/(sqrt(length(P)))),
    #se.1=std.error(Mg), 
    P = mean(P, na.rm = TRUE)
    )
df.summaryP

P1<-lm(P~Treatment+Block+Site+Date,data=DF)
summary(P1)

P2<-aov(P1)
summary(P2)

tukey.testP<-HSD.test(P2,trt="Treatment")
tukey.testP
```

Data Visualization P

```{r}
ggplot(df.summaryP, aes(Date, P, color = Treatment)) +
  geom_jitter(position = position_jitter(0.2)) + 
  geom_line(aes(group = Treatment),data = df.summaryP) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)
  )+
  geom_errorbar(aes(ymin = P-se, ymax = P+se), data = df.summaryP, width = 0.2)+
 
  theme(legend.position = "top")+
  ylab("Phosphorus (mg/L)")
```

Data Analysis EC

```{r}
df.summaryEC <- DF %>%
  group_by(Treatment, Date) %>%
  summarize(
    sd=sd(EC, na.rm = TRUE),
    se=(sd/(sqrt(length(EC)))),
    #se.1=std.error(Mg), 
    EC = mean(EC, na.rm = TRUE)
    )
df.summaryEC

EC1<-lm(EC~Treatment+Block+Site+Date,data=DF)
summary(EC1)

EC2<-aov(EC1)
summary(EC2)

tukey.testEC<-HSD.test(EC2,trt="Treatment")
tukey.testEC
```

Data Visualization EC

```{r}
ggplot(df.summaryEC, aes(Date, EC, color = Treatment)) +
  geom_jitter(position = position_jitter(0.2)) + 
  geom_line(aes(group = Treatment),data = df.summaryEC) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)
  )+
  geom_errorbar(aes(ymin = EC-se, ymax = EC+se), data = df.summaryEC, width = 0.2)+
 
  theme(legend.position = "top")+
  ylab("EC (mS/cm)")
```

Data Analysis pH

```{r}
df.summarypH <- DF %>%
  group_by(Treatment, Date) %>%
  summarize(
    sd=sd(pH, na.rm = TRUE),
    se=(sd/(sqrt(length(pH)))),
    #se.1=std.error(Mg), 
    pH = mean(pH, na.rm = TRUE)
    )
df.summarypH

pH1<-lm(pH~Treatment+Block+Site+Date,data=DF)
summary(pH1)

pH2<-aov(pH1)
summary(pH2)

tukey.testpH<-HSD.test(pH2,trt="Treatment")
tukey.testpH
```

Data Visualization pH

```{r}
ggplot(df.summarypH, aes(Date, pH, color = Treatment)) +
  geom_jitter(position = position_jitter(0.2)) + 
  geom_line(aes(group = Treatment),data = df.summarypH) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)
  )+
  geom_errorbar(aes(ymin = pH-se, ymax = pH+se), data = df.summarypH, width = 0.2)+
 
  theme(legend.position = "top")+
  ylab("pH")
```
